# coding: utf-8

"""
    Token-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ks_api_client
from ks_api_client.api.token_api import TokenApi  # noqa: E501
from ks_api_client.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = ks_api_client.api.token_api.TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_revoke_post(self):
        """Test case for revoke_post

        """
        pass

    def test_token_post(self):
        """Test case for token_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
